TEXT_GAMEOVER   = "CONGRATULATIONS!";
TEXT_SCORE      = "SCORE";
TEXT_STAGE      = "STAGE";
TEXT_TOTAL_SCORE = "TOTAL SCORE";
TEXT_ARE_SURE = "ARE YOU SURE?";

TEXT_WIDE_RIGHT = "WIDE RIGHT!";
TEXT_WIDE_LEFT = "WIDE LEFT!";
TEXT_CENTER_NULL = "POLE HIT!";
TEXT_CENTER_RED = "NOT BAD!";
TEXT_CENTER_YELLOW = "GOOD!";
TEXT_CENTER_GREEN = "SUPER!";

TEXT_HELP1     = "PRESS SPACEBAR TO CHOOSE THE POINT WHERE KICKING THE BALL";
TEXT_HELP1_MOB = "TAP ON THE SCREEN TO CHOOSE THE POINT WHERE KICKING THE BALL";

TEXT_HELP2     = "CENTER THE GREEN AREA TO GET THE TOP SCORE!";
var TEXT_PRELOADER_CONTINUE = "START";


TEXT_SHARE_IMAGE = "200x200.jpg";
TEXT_SHARE_TITLE = "Congratulations!";
TEXT_SHARE_MSG1 = "You collected <strong>";
TEXT_SHARE_MSG2 = " points</strong>!<br><br>Share your score with your friends!";
TEXT_SHARE_SHARE1 = "My score is ";
TEXT_SHARE_SHARE2 = " points! Can you do better";