(function(){var b="undefined"!==typeof window&&"undefined"!==typeof window.document?window.document:{},d="undefined"!==typeof module&&module.exports,a="undefined"!==typeof Element&&"ALLOW_KEYBOARD_INPUT"in Element,c=function(){for(var g,k=["requestFullscreen exitFullscreen fullscreenElement fullscreenEnabled fullscreenchange fullscreenerror".split(" "),"webkitRequestFullscreen webkitExitFullscreen webkitFullscreenElement webkitFullscreenEnabled webkitfullscreenchange webkitfullscreenerror".split(" "),
"webkitRequestFullScreen webkitCancelFullScreen webkitCurrentFullScreenElement webkitCancelFullScreen webkitfullscreenchange webkitfullscreenerror".split(" "),"mozRequestFullScreen mozCancelFullScreen mozFullScreenElement mozFullScreenEnabled mozfullscreenchange mozfullscreenerror".split(" "),"msRequestFullscreen msExitFullscreen msFullscreenElement msFullscreenEnabled MSFullscreenChange MSFullscreenError".split(" ")],e=0,l=k.length,q={};e<l;e++)if((g=k[e])&&g[1]in b){for(e=0;e<g.length;e++)q[k[0][e]]=
g[e];return q}return!1}(),f={change:c.fullscreenchange,error:c.fullscreenerror},h={request:function(g){var k=c.requestFullscreen;g=g||b.documentElement;if(/5\.1[.\d]* Safari/.test(navigator.userAgent))g[k]();else g[k](a&&Element.ALLOW_KEYBOARD_INPUT)},exit:function(){b[c.exitFullscreen]()},toggle:function(g){this.isFullscreen?this.exit():this.request(g)},onchange:function(g){this.on("change",g)},onerror:function(g){this.on("error",g)},on:function(g,k){var e=f[g];e&&b.addEventListener(e,k,!1)},off:function(g,
k){var e=f[g];e&&b.removeEventListener(e,k,!1)},raw:c};c?(Object.defineProperties(h,{isFullscreen:{get:function(){return!!b[c.fullscreenElement]}},element:{enumerable:!0,get:function(){return b[c.fullscreenElement]}},enabled:{enumerable:!0,get:function(){return!!b[c.fullscreenEnabled]}}}),d?module.exports=h:window.screenfull=h):d?module.exports=!1:window.screenfull=!1})();var s_iScaleFactor=1,s_iOffsetX,s_iOffsetY,s_bIsIphone=!1;
(function(b){(jQuery.browser=jQuery.browser||{}).mobile=/android|avantgo|bada\/|blackberry|blazer|compal|elaine|fennec|hiptop|iemobile|ip(ad|hone|od)|iris|kindle|lge |maemo|midp|mmp|netfront|opera m(ob|in)i|palm( os)?|phone|p(ixi|re)\/|plucker|pocket|psp|symbian|tablet|treo|up\.(browser|link)|vodafone|wap|webos|windows (ce|phone)|xda|xiino/i.test(b)||/1207|6310|6590|3gso|4thp|50[1-6]i|770s|802s|a wa|abac|ac(er|oo|s\-)|ai(ko|rn)|al(av|ca|co)|amoi|an(ex|ny|yw)|aptu|ar(ch|go)|as(te|us)|attw|au(di|\-m|r |s )|avan|be(ck|ll|nq)|bi(lb|rd)|bl(ac|az)|br(e|v)w|bumb|bw\-(n|u)|c55\/|capi|ccwa|cdm\-|cell|chtm|cldc|cmd\-|co(mp|nd)|craw|da(it|ll|ng)|dbte|dc\-s|devi|dica|dmob|do(c|p)o|ds(12|\-d)|el(49|ai)|em(l2|ul)|er(ic|k0)|esl8|ez([4-7]0|os|wa|ze)|fetc|fly(\-|_)|g1 u|g560|gene|gf\-5|g\-mo|go(\.w|od)|gr(ad|un)|haie|hcit|hd\-(m|p|t)|hei\-|hi(pt|ta)|hp( i|ip)|hs\-c|ht(c(\-| |_|a|g|p|s|t)|tp)|hu(aw|tc)|i\-(20|go|ma)|i230|iac( |\-|\/)|ibro|idea|ig01|ikom|im1k|inno|ipaq|iris|ja(t|v)a|jbro|jemu|jigs|kddi|keji|kgt( |\/)|klon|kpt |kwc\-|kyo(c|k)|le(no|xi)|lg( g|\/(k|l|u)|50|54|e\-|e\/|\-[a-w])|libw|lynx|m1\-w|m3ga|m50\/|ma(te|ui|xo)|mc(01|21|ca)|m\-cr|me(di|rc|ri)|mi(o8|oa|ts)|mmef|mo(01|02|bi|de|do|t(\-| |o|v)|zz)|mt(50|p1|v )|mwbp|mywa|n10[0-2]|n20[2-3]|n30(0|2)|n50(0|2|5)|n7(0(0|1)|10)|ne((c|m)\-|on|tf|wf|wg|wt)|nok(6|i)|nzph|o2im|op(ti|wv)|oran|owg1|p800|pan(a|d|t)|pdxg|pg(13|\-([1-8]|c))|phil|pire|pl(ay|uc)|pn\-2|po(ck|rt|se)|prox|psio|pt\-g|qa\-a|qc(07|12|21|32|60|\-[2-7]|i\-)|qtek|r380|r600|raks|rim9|ro(ve|zo)|s55\/|sa(ge|ma|mm|ms|ny|va)|sc(01|h\-|oo|p\-)|sdk\/|se(c(\-|0|1)|47|mc|nd|ri)|sgh\-|shar|sie(\-|m)|sk\-0|sl(45|id)|sm(al|ar|b3|it|t5)|so(ft|ny)|sp(01|h\-|v\-|v )|sy(01|mb)|t2(18|50)|t6(00|10|18)|ta(gt|lk)|tcl\-|tdg\-|tel(i|m)|tim\-|t\-mo|to(pl|sh)|ts(70|m\-|m3|m5)|tx\-9|up(\.b|g1|si)|utst|v400|v750|veri|vi(rg|te)|vk(40|5[0-3]|\-v)|vm40|voda|vulc|vx(52|53|60|61|70|80|81|83|85|98)|w3c(\-| )|webc|whit|wi(g |nc|nw)|wmlb|wonu|x700|xda(\-|2|g)|yas\-|your|zeto|zte\-/i.test(b.substr(0,
4))})(navigator.userAgent||navigator.vendor||window.opera);$(window).resize(function(){sizeHandler()});function trace(b){console.log(b)}
function getSize(b){var d=b.toLowerCase(),a=window.document,c=a.documentElement;if(void 0===window["inner"+b])b=c["client"+b];else if(window["inner"+b]!=c["client"+b]){var f=a.createElement("body");f.id="vpw-test-b";f.style.cssText="overflow:scroll";var h=a.createElement("div");h.id="vpw-test-d";h.style.cssText="position:absolute;top:-1000px";h.innerHTML="<style>@media("+d+":"+c["client"+b]+"px){body#vpw-test-b div#vpw-test-d{"+d+":7px!important}}</style>";f.appendChild(h);c.insertBefore(f,a.head);
b=7==h["offset"+b]?c["client"+b]:window["inner"+b];c.removeChild(f)}else b=window["inner"+b];return b}window.addEventListener("orientationchange",onOrientationChange);function onOrientationChange(){window.matchMedia("(orientation: portrait)").matches&&sizeHandler();window.matchMedia("(orientation: landscape)").matches&&sizeHandler()}function isChrome(){return/Chrome/.test(navigator.userAgent)&&/Google Inc/.test(navigator.vendor)}
function isIOS(){var b="iPad Simulator;iPhone Simulator;iPod Simulator;iPad;iPhone;iPod".split(";");for(-1!==navigator.userAgent.toLowerCase().indexOf("iphone")&&(s_bIsIphone=!0);b.length;)if(navigator.platform===b.pop())return!0;return s_bIsIphone=!1}function getIOSWindowHeight(){return document.documentElement.clientWidth/window.innerWidth*window.innerHeight}function getHeightOfIOSToolbars(){var b=(0===window.orientation?screen.height:screen.width)-getIOSWindowHeight();return 1<b?b:0}
function sizeHandler(){window.scrollTo(0,1);if($("#canvas")){var b=navigator.userAgent.match(/(iPad|iPhone|iPod)/g)?getIOSWindowHeight():getSize("Height");var d=getSize("Width");_checkOrientation(d,b);var a=Math.min(b/CANVAS_HEIGHT,d/CANVAS_WIDTH),c=CANVAS_WIDTH*a;a*=CANVAS_HEIGHT;if(s_bMobile&&!s_bIsIphone)$("#canvas").css("width",c+"px"),$("#canvas").css("height",a+"px");else{s_oStage.canvas.width=c;s_oStage.canvas.height=a;var f=Math.min(c/CANVAS_WIDTH,a/CANVAS_HEIGHT);s_oStage.scaleX=s_oStage.scaleY=
f}if(a<b){var h=b-a;a+=h;c+=CANVAS_WIDTH/CANVAS_HEIGHT*h}else c<d&&(h=d-c,c+=h,a+=CANVAS_HEIGHT/CANVAS_WIDTH*h);h=b/2-a/2;var g=d/2-c/2;f=CANVAS_WIDTH/c;if(g*f<-EDGEBOARD_X||h*f<-EDGEBOARD_Y)a=Math.min(b/(CANVAS_HEIGHT-2*EDGEBOARD_Y),d/(CANVAS_WIDTH-2*EDGEBOARD_X)),c=CANVAS_WIDTH*a,a*=CANVAS_HEIGHT,h=(b-a)/2,g=(d-c)/2,f=CANVAS_WIDTH/c;s_iOffsetX=-1*g*f;s_iOffsetY=-1*h*f;0<=h&&(s_iOffsetY=0);0<=g&&(s_iOffsetX=0);null!==s_oInterface&&s_oInterface.refreshButtonPos(s_iOffsetX,s_iOffsetY);null!==s_oMenu&&
s_oMenu.refreshButtonPos(s_iOffsetX,s_iOffsetY);s_bIsIphone?(canvas=document.getElementById("canvas"),s_oStage.canvas.width=2*c,s_oStage.canvas.height=2*a,canvas.style.width=c+"px",canvas.style.height=a+"px",f=Math.min(c/CANVAS_WIDTH,a/CANVAS_HEIGHT),s_oStage.scaleX=s_oStage.scaleY=2*f):s_bMobile||isChrome()?($("#canvas").css("width",c+"px"),$("#canvas").css("height",a+"px")):(s_oStage.canvas.width=c,s_oStage.canvas.height=a,s_iScaleFactor=Math.min(c/CANVAS_WIDTH,a/CANVAS_HEIGHT),s_oStage.scaleX=
s_oStage.scaleY=s_iScaleFactor);0>h||(h=(b-a)/2);$("#canvas").css("top",h+"px");$("#canvas").css("left",g+"px");fullscreenHandler()}}
function _checkOrientation(b,d){s_bMobile&&ENABLE_CHECK_ORIENTATION&&(b>d?"landscape"===$(".orientation-msg-container").attr("data-orientation")?($(".orientation-msg-container").css("display","none"),s_oMain.startUpdate()):($(".orientation-msg-container").css("display","block"),s_oMain.stopUpdate()):"portrait"===$(".orientation-msg-container").attr("data-orientation")?($(".orientation-msg-container").css("display","none"),s_oMain.startUpdate()):($(".orientation-msg-container").css("display","block"),
s_oMain.stopUpdate()))}function playSound(b,d,a){return!1===DISABLE_SOUND_MOBILE||!1===s_bMobile?(s_aSounds[b].play(),s_aSounds[b].volume(d),s_aSounds[b].loop(a),s_aSounds[b]):null}function stopSound(b){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||s_aSounds[b].stop()}function setVolume(b,d){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||s_aSounds[b].volume(d)}function setMute(b,d){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||s_aSounds[b].mute(d)}
function createBitmap(b,d,a){var c=new createjs.Bitmap(b),f=new createjs.Shape;d&&a?f.graphics.beginFill("#fff").drawRect(0,0,d,a):f.graphics.beginFill("#ff0").drawRect(0,0,b.width,b.height);c.hitArea=f;return c}function createSprite(b,d,a,c,f,h){b=null!==d?new createjs.Sprite(b,d):new createjs.Sprite(b);d=new createjs.Shape;d.graphics.beginFill("#000000").drawRect(-a,-c,f,h);b.hitArea=d;return b}function pad(b,d,a){b+="";return b.length>=d?b:Array(d-b.length+1).join(a||"0")+b}
function randomFloatBetween(b,d,a){"undefined"===typeof a&&(a=2);return parseFloat(Math.min(b+Math.random()*(d-b),d).toFixed(a))}function rotateVector2D(b,d){var a=d.getX()*Math.cos(b)+d.getY()*Math.sin(b),c=d.getX()*-Math.sin(b)+d.getY()*Math.cos(b);d.set(a,c)}function tweenVectorsOnX(b,d,a){return b+a*(d-b)}function shuffle(b){for(var d=b.length,a,c;0!==d;)c=Math.floor(Math.random()*d),--d,a=b[d],b[d]=b[c],b[c]=a;return b}
function bubbleSort(b){do{var d=!1;for(var a=0;a<b.length-1;a++)b[a]>b[a+1]&&(d=b[a],b[a]=b[a+1],b[a+1]=d,d=!0)}while(d)}function compare(b,d){return b.index>d.index?-1:b.index<d.index?1:0}function easeLinear(b,d,a,c){return a*b/c+d}function easeInQuad(b,d,a,c){return a*(b/=c)*b+d}function easeInSine(b,d,a,c){return-a*Math.cos(b/c*(Math.PI/2))+a+d}function easeInCubic(b,d,a,c){return a*(b/=c)*b*b+d}
function getTrajectoryPoint(b,d){var a=new createjs.Point,c=(1-b)*(1-b),f=b*b;a.x=c*d.start.x+2*(1-b)*b*d.traj.x+f*d.end.x;a.y=c*d.start.y+2*(1-b)*b*d.traj.y+f*d.end.y;return a}function formatTime(b){b/=1E3;var d=Math.floor(b/60);b=parseFloat(b-60*d).toFixed(1);var a="";a=10>d?a+("0"+d+":"):a+(d+":");return 10>b?a+("0"+b):a+b}function degreesToRadians(b){return b*Math.PI/180}function checkRectCollision(b,d){var a=getBounds(b,.9);var c=getBounds(d,.98);return calculateIntersection(a,c)}
function calculateIntersection(b,d){var a,c,f,h;var g=b.x+(a=b.width/2);var k=b.y+(c=b.height/2);var e=d.x+(f=d.width/2);var l=d.y+(h=d.height/2);g=Math.abs(g-e)-(a+f);k=Math.abs(k-l)-(c+h);return 0>g&&0>k?(g=Math.min(Math.min(b.width,d.width),-g),k=Math.min(Math.min(b.height,d.height),-k),{x:Math.max(b.x,d.x),y:Math.max(b.y,d.y),width:g,height:k,rect1:b,rect2:d}):null}
function getBounds(b,d){var a={x:Infinity,y:Infinity,width:0,height:0};if(b instanceof createjs.Container){a.x2=-Infinity;a.y2=-Infinity;var c=b.children,f=c.length,h;for(h=0;h<f;h++){var g=getBounds(c[h],1);g.x<a.x&&(a.x=g.x);g.y<a.y&&(a.y=g.y);g.x+g.width>a.x2&&(a.x2=g.x+g.width);g.y+g.height>a.y2&&(a.y2=g.y+g.height)}Infinity==a.x&&(a.x=0);Infinity==a.y&&(a.y=0);Infinity==a.x2&&(a.x2=0);Infinity==a.y2&&(a.y2=0);a.width=a.x2-a.x;a.height=a.y2-a.y;delete a.x2;delete a.y2}else{if(b instanceof createjs.Bitmap){f=
b.sourceRect||b.image;h=f.width*d;var k=f.height*d}else if(b instanceof createjs.Sprite)if(b.spriteSheet._frames&&b.spriteSheet._frames[b.currentFrame]&&b.spriteSheet._frames[b.currentFrame].image){f=b.spriteSheet.getFrame(b.currentFrame);h=f.rect.width;k=f.rect.height;c=f.regX;var e=f.regY}else a.x=b.x||0,a.y=b.y||0;else a.x=b.x||0,a.y=b.y||0;c=c||0;h=h||0;e=e||0;k=k||0;a.regX=c;a.regY=e;f=b.localToGlobal(0-c,0-e);g=b.localToGlobal(h-c,k-e);h=b.localToGlobal(h-c,0-e);c=b.localToGlobal(0-c,k-e);a.x=
Math.min(Math.min(Math.min(f.x,g.x),h.x),c.x);a.y=Math.min(Math.min(Math.min(f.y,g.y),h.y),c.y);a.width=Math.max(Math.max(Math.max(f.x,g.x),h.x),c.x)-a.x;a.height=Math.max(Math.max(Math.max(f.y,g.y),h.y),c.y)-a.y}return a}function NoClickDelay(b){this.element=b;window.Touch&&this.element.addEventListener("touchstart",this,!1)}function shuffle(b){for(var d=b.length,a,c;0<d;)c=Math.floor(Math.random()*d),d--,a=b[d],b[d]=b[c],b[c]=a;return b}
NoClickDelay.prototype={handleEvent:function(b){switch(b.type){case "touchstart":this.onTouchStart(b);break;case "touchmove":this.onTouchMove(b);break;case "touchend":this.onTouchEnd(b)}},onTouchStart:function(b){b.preventDefault();this.moved=!1;this.element.addEventListener("touchmove",this,!1);this.element.addEventListener("touchend",this,!1)},onTouchMove:function(b){this.moved=!0},onTouchEnd:function(b){this.element.removeEventListener("touchmove",this,!1);this.element.removeEventListener("touchend",
this,!1);if(!this.moved){b=document.elementFromPoint(b.changedTouches[0].clientX,b.changedTouches[0].clientY);3==b.nodeType&&(b=b.parentNode);var d=document.createEvent("MouseEvents");d.initEvent("click",!0,!0);b.dispatchEvent(d)}}};
(function(){function b(a){var c={focus:"visible",focusin:"visible",pageshow:"visible",blur:"hidden",focusout:"hidden",pagehide:"hidden"};a=a||window.event;a.type in c?document.body.className=c[a.type]:(document.body.className=this[d]?"hidden":"visible","hidden"===document.body.className?s_oMain.stopUpdate():s_oMain.startUpdate())}var d="hidden";d in document?document.addEventListener("visibilitychange",b):(d="mozHidden")in document?document.addEventListener("mozvisibilitychange",b):(d="webkitHidden")in
document?document.addEventListener("webkitvisibilitychange",b):(d="msHidden")in document?document.addEventListener("msvisibilitychange",b):"onfocusin"in document?document.onfocusin=document.onfocusout=b:window.onpageshow=window.onpagehide=window.onfocus=window.onblur=b})();function ctlArcadeResume(){null!==s_oMain&&s_oMain.startUpdate()}function ctlArcadePause(){null!==s_oMain&&s_oMain.stopUpdate()}
function getParamValue(b){for(var d=window.location.search.substring(1).split("&"),a=0;a<d.length;a++){var c=d[a].split("=");if(c[0]==b)return c[1]}}function fullscreenHandler(){ENABLE_FULLSCREEN&&screenfull.enabled&&(s_bFullscreen=screen.height<window.innerHeight+3&&screen.height>window.innerHeight-3?!0:!1,null!==s_oInterface&&s_oInterface.resetFullscreenBut(),null!==s_oMenu&&s_oMenu.resetFullscreenBut())}
if(screenfull.enabled)screenfull.on("change",function(){s_bFullscreen=screenfull.isFullscreen;null!==s_oInterface&&s_oInterface.resetFullscreenBut();null!==s_oMenu&&s_oMenu.resetFullscreenBut()});var s_szGameID="056d07a4e77f47c6bfe26f4f9dbeb919";window.GD_OPTIONS={gameId:s_szGameID,onEvent:function(b){switch(b.name){case "SDK_GAME_START":s_oMain&&s_oMain.startUpdate();break;case "SDK_GAME_PAUSE":s_oMain&&s_oMain.stopUpdate()}}};
(function(b,d,a){var c=b.getElementsByTagName(d)[0];b.getElementById(a)||(b=b.createElement(d),b.id=a,b.src="/main.min.js",c.parentNode.insertBefore(b,c))})(document,"script","gamedistribution-jssdk");
function CSpriteLibrary(){var b={},d,a,c,f,h,g;this.init=function(k,e,l){d={};c=a=0;f=k;h=e;g=l};this.addSprite=function(k,e){if(!b.hasOwnProperty(k)){var l=new Image;b[k]=d[k]={szPath:e,oSprite:l,bLoaded:!1};a++}};this.getSprite=function(k){return b.hasOwnProperty(k)?b[k].oSprite:null};this._onSpritesLoaded=function(){a=0;h.call(g)};this._onSpriteLoaded=function(){f.call(g);++c===a&&this._onSpritesLoaded()};this.loadSprites=function(){for(var k in d)d[k].oSprite.oSpriteLibrary=this,d[k].oSprite.szKey=
k,d[k].oSprite.onload=function(){this.oSpriteLibrary.setLoaded(this.szKey);this.oSpriteLibrary._onSpriteLoaded(this.szKey)},d[k].oSprite.onerror=function(e){var l=e.currentTarget;setTimeout(function(){d[l.szKey].oSprite.src=d[l.szKey].szPath},500)},d[k].oSprite.src=d[k].szPath};this.setLoaded=function(k){b[k].bLoaded=!0};this.isLoaded=function(k){return b[k].bLoaded};this.getNumSprites=function(){return a}}
var CANVAS_WIDTH=640,CANVAS_HEIGHT=1024,EDGEBOARD_X=16,EDGEBOARD_Y=110,FPS=30,FPS_TIME=1E3/FPS,DISABLE_SOUND_MOBILE=!1,PRIMARY_FONT="space_marine",SPACE_BAR=32,LEFT=37,RIGHT=39,UP=38,DOWN=40,STATE_LOADING=0,STATE_MENU=1,STATE_HELP=1,STATE_GAME=3,ON_MOUSE_DOWN=0,ON_MOUSE_UP=1,ON_MOUSE_OVER=2,ON_MOUSE_OUT=3,ON_DRAG_START=4,ON_DRAG_END=5,ON_CONTROLLER_END=8,ON_CONTROLLER_REMOVE=9,ON_CONTROLLER_ROLL=10,HORIZONTAL_SELECTION_STATE=0,VERTICAL_SELECTION_STATE=1,SHOT_SELECTION_STATE=2,NULL_TARGET_RIGHT=-3,
NULL_TARGET_LEFT=-2,NULL_TARGET_POLE=-1,RED_TARGET=0,YELLOW_TARGET=1,GREEN_TARGET=2,NUM_STAGES=5,BALL_FLYTIME=2500,BALL_MAX_ROTATION=30,SHOT_INDICATOR_SPEED,DECREASE_SHOT_INDICATOR_SPEED,SHOTS_PER_STAGE,RED_AREA_POINTS,YELLOW_AREA_POINTS,GREEN_AREA_POINTS,AD_SHOW_COUNTER,ENABLE_FULLSCREEN,ENABLE_CHECK_ORIENTATION,GOAL_AREA=[{x:0,y:-40,width:750,height:435},{x:-26,y:-94,width:750,height:420},{x:-18,y:-78,width:750,height:400},{x:16,y:-206,width:750,height:500},{x:-34,y:-202,width:750,height:500}],
STAKE_POS=[[{x:-160,y:-260},{x:-165,y:190},{x:165,y:190},{x:160,y:-260}],[{x:-185,y:-300},{x:-190,y:170},{x:140,y:150},{x:135,y:-350}],[{x:-170,y:-330},{x:-175,y:165},{x:140,y:180},{x:140,y:-280}],[{x:-120,y:-530},{x:-125,y:90},{x:155,y:135},{x:150,y:-400}],[{x:-145,y:-400},{x:-150,y:140},{x:80,y:90},{x:75,y:-540}]],POST_POS=[{x:0,y:66},{x:-26,y:20},{x:-18,y:34},{x:-4,y:-70},{x:12,y:-70}],TARGET_AREA_SPRITE_OFFSET=[{red:{x:0,y:0},yellow:{x:0,y:0},green:{x:0,y:0}},{red:{x:0,y:0},yellow:{x:4,y:-6},
green:{x:5,y:-9}},{red:{x:0,y:0},yellow:{x:-3,y:-6},green:{x:-4,y:-9}},{red:{x:0,y:0},yellow:{x:-6,y:-18},green:{x:-9,y:-27}},{red:{x:0,y:0},yellow:{x:6,y:-20},green:{x:8,y:-30}}],Y_BAR_OFFSET=[-150,-150,-150,-180,-180],GREEN_INDICATOR_RANGE=[{horiz:{left:-14,right:14},vert:{top:-29,bot:24}},{horiz:{left:-17,right:11},vert:{top:-25,bot:32}},{horiz:{left:-12,right:15},vert:{top:-25,bot:32}},{horiz:{left:-7,right:16},vert:{top:-23,bot:39}},{horiz:{left:-13,right:4},vert:{top:-11,bot:39}}];
function CPreloader(){var b,d,a,c,f,h,g,k,e,l;this._init=function(){s_oSpriteLibrary.init(this._onImagesLoaded,this._onAllImagesLoaded,this);s_oSpriteLibrary.addSprite("progress_bar","./sprites/progress_bar.png");s_oSpriteLibrary.addSprite("200x200","./sprites/200x200.jpg");s_oSpriteLibrary.addSprite("but_start","./sprites/but_start.png");s_oSpriteLibrary.loadSprites();l=new createjs.Container;s_oStage.addChild(l)};this.unload=function(){e.unload();l.removeAllChildren()};this._onImagesLoaded=function(){};
this._onAllImagesLoaded=function(){this.attachSprites();s_oMain.preloaderReady()};this.attachSprites=function(){var q=new createjs.Shape;q.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);l.addChild(q);q=s_oSpriteLibrary.getSprite("200x200");g=createBitmap(q);g.regX=.5*q.width;g.regY=.5*q.height;g.x=CANVAS_WIDTH/2;g.y=CANVAS_HEIGHT/2-80;l.addChild(g);k=new createjs.Shape;k.graphics.beginFill("rgba(0,0,0,0.01)").drawRoundRect(g.x-100,g.y-100,200,200,10);l.addChild(k);g.mask=k;q=
s_oSpriteLibrary.getSprite("progress_bar");c=createBitmap(q);c.x=CANVAS_WIDTH/2-q.width/2;c.y=CANVAS_HEIGHT/2+70;l.addChild(c);b=q.width;d=q.height;f=new createjs.Shape;f.graphics.beginFill("rgba(0,0,0,0.01)").drawRect(c.x,c.y,1,d);l.addChild(f);c.mask=f;a=new createjs.Text("","30px "+PRIMARY_FONT,"#fff");a.x=CANVAS_WIDTH/2;a.y=CANVAS_HEIGHT/2+120;a.textBaseline="alphabetic";a.textAlign="center";l.addChild(a);q=s_oSpriteLibrary.getSprite("but_start");e=new CTextButton(CANVAS_WIDTH/2,CANVAS_HEIGHT/
2+100,q,TEXT_PRELOADER_CONTINUE,"Arial","#000",36,l);e.addEventListener(ON_MOUSE_UP,this._onButStartRelease,this);e.setVisible(!1);h=new createjs.Shape;h.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);l.addChild(h);createjs.Tween.get(h).to({alpha:0},500).call(function(){createjs.Tween.removeTweens(h);l.removeChild(h)})};this._onButStartRelease=function(){s_oMain._allResourcesLoaded()};this.refreshLoader=function(q){a.text=q+"%";100===q&&(e.setVisible(!0),a.visible=!1,c.visible=
!1);f.graphics.clear();q=Math.floor(q*b/100);f.graphics.beginFill("rgba(0,0,0,0.01)").drawRect(c.x,c.y,q,d)};this._init()}
function CMain(b){var d,a=0,c=0,f=STATE_LOADING,h,g;this.initContainer=function(){s_oCanvas=document.getElementById("canvas");s_oStage=new createjs.Stage(s_oCanvas);s_oStage.preventSelection=!1;createjs.Touch.enable(s_oStage);s_bMobile=jQuery.browser.mobile;!1===s_bMobile&&(s_oStage.enableMouseOver(20),$("body").on("contextmenu","#canvas",function(e){return!1}));s_iPrevTime=(new Date).getTime();createjs.Ticker.addEventListener("tick",this._update);createjs.Ticker.framerate=30;navigator.userAgent.match(/Windows Phone/i)&&
(DISABLE_SOUND_MOBILE=!0);s_oTweenController=new CTweenController;s_oSpriteLibrary=new CSpriteLibrary;h=new CPreloader};this.preloaderReady=function(){this._loadImages();!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||this._initSounds();d=!0};this.soundLoaded=function(){a++;h.refreshLoader(Math.floor(a/c*100))};this._initSounds=function(){var e=[];e.push({path:"./sounds/",filename:"crowd",loop:!1,volume:1,ingamename:"crowd"});e.push({path:"./sounds/",filename:"click",loop:!1,volume:1,ingamename:"click"});
e.push({path:"./sounds/",filename:"game_over",loop:!1,volume:1,ingamename:"game_over"});e.push({path:"./sounds/",filename:"kick",loop:!1,volume:1,ingamename:"kick"});e.push({path:"./sounds/",filename:"goal",loop:!1,volume:1,ingamename:"goal"});e.push({path:"./sounds/",filename:"miss_goal",loop:!1,volume:1,ingamename:"miss_goal"});e.push({path:"./sounds/",filename:"red_area",loop:!1,volume:1,ingamename:"red_area"});e.push({path:"./sounds/",filename:"yellow_area",loop:!1,volume:1,ingamename:"yellow_area"});
e.push({path:"./sounds/",filename:"green_area",loop:!1,volume:1,ingamename:"green_area"});e.push({path:"./sounds/",filename:"soundtrack",loop:!0,volume:1,ingamename:"soundtrack"});c+=e.length;s_aSounds=[];for(var l=0;l<e.length;l++)s_aSounds[e[l].ingamename]=new Howl({src:[e[l].path+e[l].filename+".mp3",e[l].path+e[l].filename+".ogg"],autoplay:!1,preload:!0,loop:e[l].loop,volume:e[l].volume,onload:s_oMain.soundLoaded()})};this._loadImages=function(){s_oSpriteLibrary.init(this._onImagesLoaded,this._onAllImagesLoaded,
this);s_oSpriteLibrary.addSprite("logo","./sprites/logo.png");s_oSpriteLibrary.addSprite("but_play","./sprites/but_play.png");s_oSpriteLibrary.addSprite("msg_box","./sprites/msg_box.png");s_oSpriteLibrary.addSprite("msg_box","./sprites/msg_box.png");s_oSpriteLibrary.addSprite("ctl_logo","./sprites/ctl_logo.png");s_oSpriteLibrary.addSprite("but_info","./sprites/but_info.png");s_oSpriteLibrary.addSprite("but_yes_big","./sprites/but_yes_big.png");s_oSpriteLibrary.addSprite("but_exit_big","./sprites/but_exit_big.png");
s_oSpriteLibrary.addSprite("but_home","./sprites/but_home.png");s_oSpriteLibrary.addSprite("arrow","./sprites/arrow.png");s_oSpriteLibrary.addSprite("but_fullscreen","./sprites/but_fullscreen.png");s_oSpriteLibrary.addSprite("bg_menu","./sprites/bg_menu.jpg");for(var e=1;5>=e;e++)s_oSpriteLibrary.addSprite("bg_game_"+e,"./sprites/bg_game_"+e+"/bg_game_"+e+".jpg"),s_oSpriteLibrary.addSprite("post_"+e,"./sprites/bg_game_"+e+"/post_"+e+".png"),s_oSpriteLibrary.addSprite("green_area_"+e,"./sprites/bg_game_"+
e+"/green_area_"+e+".png"),s_oSpriteLibrary.addSprite("yellow_area_"+e,"./sprites/bg_game_"+e+"/yellow_area_"+e+".png"),s_oSpriteLibrary.addSprite("red_area_"+e,"./sprites/bg_game_"+e+"/red_area_"+e+".png");s_oSpriteLibrary.addSprite("but_exit","./sprites/but_exit.png");s_oSpriteLibrary.addSprite("audio_icon","./sprites/audio_icon.png");s_oSpriteLibrary.addSprite("but_restart","./sprites/but_restart.png");s_oSpriteLibrary.addSprite("arrow_bar","./sprites/arrow_bar.png");s_oSpriteLibrary.addSprite("top_bar",
"./sprites/top_bar.png");s_oSpriteLibrary.addSprite("right_bar","./sprites/right_bar.png");s_oSpriteLibrary.addSprite("ball","./sprites/ball.png");s_oSpriteLibrary.addSprite("ball_holder","./sprites/ball_holder.png");for(e=0;37>=e;e++)s_oSpriteLibrary.addSprite("player_"+e,"./sprites/player/player_"+e+".png");c+=s_oSpriteLibrary.getNumSprites();s_oSpriteLibrary.loadSprites()};this._onImagesLoaded=function(){a++;h.refreshLoader(Math.floor(a/c*100))};this._onAllImagesLoaded=function(){};this._allResourcesLoaded=
function(){try{checkMoreGames(s_szGameID,"bottom-left",["casual","sport","multiplayer"],[],-1,"blue_gray")}catch(e){}h.unload();s_oSoundTrack=playSound("soundtrack",1,!0);s_oMain.gotoMenu()};this.gotoMenu=function(){try{showMoreGames()}catch(e){}new CMenu;f=STATE_MENU};this.gotoGame=function(){g=new CGame(k);f=STATE_GAME};this.gotoHelp=function(){new CHelp;f=STATE_HELP};this.stopUpdate=function(){d=!1;createjs.Ticker.paused=!0;$("#block_game").css("display","block");!1!==DISABLE_SOUND_MOBILE&&!1!==
s_bMobile||Howler.mute(!0)};this.startUpdate=function(){s_iPrevTime=(new Date).getTime();d=!0;createjs.Ticker.paused=!1;$("#block_game").css("display","none");(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)&&s_bAudioActive&&Howler.mute(!1)};this._update=function(e){if(!1!==d){var l=(new Date).getTime();s_iTimeElaps=l-s_iPrevTime;s_iCntTime+=s_iTimeElaps;s_iCntFps++;s_iPrevTime=l;1E3<=s_iCntTime&&(s_iCurFps=s_iCntFps,s_iCntTime-=1E3,s_iCntFps=0);f===STATE_GAME&&g.update();s_oStage.update(e)}};s_oMain=
this;var k=b;ENABLE_FULLSCREEN=b.fullscreen;ENABLE_CHECK_ORIENTATION=b.check_orientation;this.initContainer()}var s_bMobile,s_bAudioActive=!0,s_iCntTime=0,s_iTimeElaps=0,s_iPrevTime=0,s_iCntFps=0,s_iCurFps=0,s_oDrawLayer,s_oStage,s_oMain,s_oSpriteLibrary,s_oSoundtrack=null,s_oCanvas,s_oTweenController,s_bFullscreen=!1,s_aSounds;
function CTextButton(b,d,a,c,f,h,g,k){var e,l,q,p,t,x,m,n,r,u,y;this._init=function(v,z,B,F,C,D,E,G){e=!1;p=[];t=[];y=createBitmap(B);l=B.width;q=B.height;u=new createjs.Text(F,E+"px "+C,D);u.textAlign="center";u.textBaseline="alphabetic";u.lineWidth=.9*l;u.x=B.width/2;u.y=Math.floor(B.height/2)+15;r=new createjs.Container;r.x=v;r.y=z;r.regX=B.width/2;r.regY=B.height/2;s_bMobile||(r.cursor="pointer");r.addChild(y,u);!1!==G&&s_oStage.addChild(r);this._initListener()};this.unload=function(){r.off("mousedown",
x);r.off("pressup",m);s_oStage.removeChild(r)};this.setVisible=function(v){r.visible=v};this.setAlign=function(v){u.textAlign=v};this.enable=function(){e=!1;y.filters=[];y.cache(0,0,l,q)};this.disable=function(){e=!0;var v=(new createjs.ColorMatrix).adjustSaturation(-100).adjustBrightness(40);y.filters=[new createjs.ColorMatrixFilter(v)];y.cache(0,0,l,q)};this._initListener=function(){x=r.on("mousedown",this.buttonDown);m=r.on("pressup",this.buttonRelease)};this.addEventListener=function(v,z,B){p[v]=
z;t[v]=B};this.addEventListenerWithParams=function(v,z,B,F){p[v]=z;t[v]=B;n=F};this.buttonRelease=function(){e||(playSound("click",1,!1),r.scaleX=1,r.scaleY=1,p[ON_MOUSE_UP]&&p[ON_MOUSE_UP].call(t[ON_MOUSE_UP],n))};this.buttonDown=function(){e||(r.scaleX=.9,r.scaleY=.9,p[ON_MOUSE_DOWN]&&p[ON_MOUSE_DOWN].call(t[ON_MOUSE_DOWN]))};this.setPosition=function(v,z){r.x=v;r.y=z};this.changeText=function(v){u.text=v};this.setX=function(v){r.x=v};this.setY=function(v){r.y=v};this.getButtonImage=function(){return r};
this.getX=function(){return r.x};this.getY=function(){return r.y};this.getSprite=function(){return r};this._init(b,d,a,c,f,h,g,k);return this}
function CToggle(b,d,a,c,f){var h,g,k,e,l,q,p;this._init=function(t,x,m,n,r){g=[];k=[];var u=new createjs.SpriteSheet({images:[m],frames:{width:m.width/2,height:m.height,regX:m.width/2/2,regY:m.height/2},animations:{state_true:[0],state_false:[1]}});h=n;p=createSprite(u,"state_"+h,m.width/2/2,m.height/2,m.width/2,m.height);p.x=t;p.y=x;p.stop();r.addChild(p);this._initListener()};this.unload=function(){p.off("mousedown",e);p.off("pressup",l);s_bMobile||p.off("mouseover",q);f.removeChild(p)};this._initListener=
function(){e=p.on("mousedown",this.buttonDown);l=p.on("pressup",this.buttonRelease);s_bMobile||(q=p.on("mouseover",this.buttonOver))};this.addEventListener=function(t,x,m){g[t]=x;k[t]=m};this.setActive=function(t){h=t;p.gotoAndStop("state_"+h)};this.buttonRelease=function(){p.scaleX=1;p.scaleY=1;playSound("click",1,!1);h=!h;p.gotoAndStop("state_"+h);g[ON_MOUSE_UP]&&g[ON_MOUSE_UP].call(k[ON_MOUSE_UP],h)};this.buttonDown=function(){p.scaleX=.9;p.scaleY=.9;g[ON_MOUSE_DOWN]&&g[ON_MOUSE_DOWN].call(k[ON_MOUSE_DOWN])};
this.buttonOver=function(t){s_bMobile||(t.target.cursor="pointer")};this.setPosition=function(t,x){p.x=t;p.y=x};this._init(b,d,a,c,f)}
function CGfxButton(b,d,a,c){var f,h,g,k,e,l,q,p;this._init=function(x,m,n,r){f=!1;h=1;g=[];k=[];e=createBitmap(n);e.x=x;e.y=m;e.scaleX=e.scaleY=h;e.regX=n.width/2;e.regY=n.height/2;r.addChild(e);this._initListener()};this.unload=function(){e.off("mousedown",l);e.off("pressup",q);s_bMobile||e.off("mouseover",p);c.removeChild(e)};this.setVisible=function(x){e.visible=x};this.setClickable=function(x){f=!x};this._initListener=function(){l=e.on("mousedown",this.buttonDown);q=e.on("pressup",this.buttonRelease);
s_bMobile||(p=e.on("mouseover",this.buttonOver))};this.addEventListener=function(x,m,n){g[x]=m;k[x]=n};this.buttonRelease=function(){f||(e.scaleX=h,e.scaleY=h,g[ON_MOUSE_UP]&&g[ON_MOUSE_UP].call(k[ON_MOUSE_UP]))};this.buttonDown=function(){f||(e.scaleX=.9*h,e.scaleY=.9*h,playSound("click",1,!1),g[ON_MOUSE_DOWN]&&g[ON_MOUSE_DOWN].call(k[ON_MOUSE_DOWN]))};this.buttonOver=function(x){s_bMobile||f||(x.target.cursor="pointer")};this.pulseAnimation=function(){createjs.Tween.get(e).to({scaleX:.9*h,scaleY:.9*
h},850,createjs.Ease.quadOut).to({scaleX:h,scaleY:h},650,createjs.Ease.quadIn).call(function(){t.pulseAnimation()})};this.trembleAnimation=function(){createjs.Tween.get(e).to({rotation:5},75,createjs.Ease.quadOut).to({rotation:-5},140,createjs.Ease.quadIn).to({rotation:0},75,createjs.Ease.quadIn).wait(750).call(function(){t.trebleAnimation()})};this.setPosition=function(x,m){e.x=x;e.y=m};this.setX=function(x){e.x=x};this.setY=function(x){e.y=x};this.getButtonImage=function(){return e};this.getX=function(){return e.x};
this.getY=function(){return e.y};var t=this;this._init(b,d,a,c);return this}
function CRollingTextController(b,d,a,c,f){var h,g,k,e,l,q,p,t,x,m,n,r;this._init=function(u,y,v,z,B){t=[];x=[];l=z;this.setUpdateInfo(v);p=B;n=u;r=y;m=[]};this.unload=function(){clearInterval(q)};this.setUpdateInfo=function(u){k=parseFloat(b.text);e=u;h=0;g=Math.round(l/FPS);var y=this;q=setInterval(function(){y.update()},FPS_TIME)};this.addEventListener=function(u,y,v){t[u]=y;x[u]=v};this.addRollingListener=function(u,y,v){t[ON_CONTROLLER_ROLL]=u;x[ON_CONTROLLER_ROLL]=y;m=[];for(u=0;u<v.length;u++)m[u]=
{step:v[u],flag:!1}};this.increaseValue=function(u){};this.getTarget=function(){return n};this.update=function(){h++;if(h>g)h=0,n.text=e.toFixed(0),null!==r&&(r.text=e.toFixed(0)),clearInterval(q);else{switch(p){case EASE_BACKIN:var u=s_oTweenController.easeInBack(h,0,1,g);break;case EASE_BACKOUT:u=s_oTweenController.easeOutBack(h,0,1,g);break;case EASE_CUBIC_IN:u=s_oTweenController.easeInCubic(h,0,1,g);break;case EASE_CUBIC_OUT:u=s_oTweenController.easeOutCubic(h,0,1,g);break;case EASE_ELASTIC_OUT:u=
s_oTweenController.easeOutElastic(h,0,1,g);break;case EASE_LINEAR:u=s_oTweenController.easeLinear(h,0,1,g);break;case EASE_QUART_BACKIN:u=s_oTweenController.easeBackInQuart(h,0,1,g);break;default:u=s_oTweenController.easeLinear(h,0,1,g)}u=s_oTweenController.tweenValue(k,e,u);for(var y=0;y<m.length;y++)u>m[y].step&&!m[y].flag&&(m[y].flag=!0,null!==t[ON_CONTROLLER_ROLL]&&t[ON_CONTROLLER_ROLL].call(x[ON_CONTROLLER_ROLL],y));n.text=u.toFixed(0);null!==r&&(r.text=u.toFixed(0))}};this._init(b,d,a,c,f)}
var EASE_LINEAR=0,EASE_CUBIC_IN=1,EASE_QUART_BACKIN=2,EASE_BACKIN=3,EASE_SIN_IN=4,EASE_QUAD_IN=5,EASE_CUBIC_OUT=6,EASE_ELASTIC_OUT=7,EASE_BACKOUT=8,EASE_QUINT_OUT=9,EASE_CUBIC_INOUT=10;
function CTweenController(){this.tweenValue=function(b,d,a){return b+a*(d-b)};this.easeLinear=function(b,d,a,c){return a*b/c+d};this.easeInCubic=function(b,d,a,c){c=(b/=c)*b*b;return d+a*c};this.easeBackInQuart=function(b,d,a,c){c=(b/=c)*b;return d+a*(2*c*c+2*c*b+-3*c)};this.easeInBack=function(b,d,a,c){return a*(b/=c)*b*(2.70158*b-1.70158)+d};this.easeInSine=function(b,d,a,c){return-a*Math.cos(b/c*(Math.PI/2))+a+d};this.easeInQuad=function(b,d,a,c){return a*(b/=c)*b+d};this.easeOutCubic=function(b,
d,a,c){return a*((b=b/c-1)*b*b+1)+d};this.easeOutElastic=function(b,d,a,c){if(0===b)return d;if(1===(b/=c))return d+a;var f=.3*c;return a*Math.pow(2,-10*b)*Math.sin(2*(b*c-f/4)*Math.PI/f)+a+d};this.easeOutBack=function(b,d,a,c){return a*((b=b/c-1)*b*(2.70158*b+1.70158)+1)+d};this.easeInOutCubic=function(b,d,a,c){return 1>(b/=c/2)?a/2*b*b*b+d:a/2*((b-=2)*b*b+2)+d};this.easeOutQuint=function(b,d,a,c){return a*((b=b/c-1)*b*b*b*b+1)+d}}
function CMenu(){var b,d,a,c,f,h,g,k,e,l,q,p,t,x,m,n,r,u=null,y=null;this._init=function(){q=createBitmap(s_oSpriteLibrary.getSprite("bg_menu"));s_oStage.addChild(q);e=80;l=50;var v=s_oSpriteLibrary.getSprite("logo");n=createBitmap(v);n.x=e;n.y=l;s_oStage.addChild(n);v=s_oSpriteLibrary.getSprite("but_play");g=CANVAS_WIDTH-v.height/2-50;k=CANVAS_HEIGHT-v.height/2-50;p=new CGfxButton(g,k,v,s_oStage);p.addEventListener(ON_MOUSE_UP,this._onButPlayRelease,this);!1===DISABLE_SOUND_MOBILE||!1===s_bMobile?
(v=s_oSpriteLibrary.getSprite("audio_icon"),a=CANVAS_WIDTH-v.height/2-10,c=v.height/2+10,x=new CToggle(a,c,v,s_bAudioActive,s_oStage),x.addEventListener(ON_MOUSE_UP,this._onAudioToggle,this),v=s_oSpriteLibrary.getSprite("but_info"),f=CANVAS_WIDTH-v.width/2-80):(v=s_oSpriteLibrary.getSprite("but_info"),f=CANVAS_WIDTH-v.height/2-10);h=v.height/2+10;m=new CGfxButton(f,h,v,s_oStage);m.addEventListener(ON_MOUSE_UP,this._onCreditsBut,this);v=window.document;var z=v.documentElement;u=z.requestFullscreen||
z.mozRequestFullScreen||z.webkitRequestFullScreen||z.msRequestFullscreen;y=v.exitFullscreen||v.mozCancelFullScreen||v.webkitExitFullscreen||v.msExitFullscreen;!1===ENABLE_FULLSCREEN&&(u=!1);u&&screenfull.enabled&&(v=s_oSpriteLibrary.getSprite("but_fullscreen"),b=v.width/4+10,d=h,r=new CToggle(b,d,v,s_bFullscreen,s_oStage),r.addEventListener(ON_MOUSE_UP,this._onFullscreenRelease,this));t=new createjs.Shape;t.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);s_oStage.addChild(t);
createjs.Tween.get(t).to({alpha:0},1E3).call(function(){t.visible=!1});this.refreshButtonPos(s_iOffsetX,s_iOffsetY)};this.unload=function(){p.unload();p=null;t.visible=!1;m.unload();if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)x.unload(),x=null;u&&screenfull.enabled&&r.unload();s_oStage.removeAllChildren();s_oMenu=q=null};this.refreshButtonPos=function(v,z){m.setPosition(f-v,z+h);!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||x.setPosition(a-v,z+c);u&&screenfull.enabled&&r.setPosition(b+s_iOffsetX,d+
s_iOffsetY);p.setPosition(g-v,k-z);n.x=e+v;n.y=l+z};this._onAudioToggle=function(){Howler.mute(s_bAudioActive);s_bAudioActive=!s_bAudioActive};this._onCreditsBut=function(){new CCreditsPanel};this._onButPlayRelease=function(){"undefined"!==typeof gdsdk&&"undefined"!==gdsdk.showAd&&gdsdk.showAd();try{hideMoreGames()}catch(v){}this.unload();$(s_oMain).trigger("start_session");s_oMain.gotoGame()};this.resetFullscreenBut=function(){u&&screenfull.enabled&&r.setActive(s_bFullscreen)};this._onFullscreenRelease=
function(){s_bFullscreen?y.call(window.document):u.call(window.document.documentElement);sizeHandler()};s_oMenu=this;this._init()}var s_oMenu=null;
function CGame(b){var d,a,c,f,h,g,k=null,e,l,q,p,t,x;this._init=function(){d=0;c=a=1;playSound("crowd",1,!0);p=new createjs.Container;p.x=CANVAS_WIDTH/2;p.y=CANVAS_HEIGHT/2;p.scaleX=p.scaleY=.5;s_oStage.addChild(p);var n=s_oSpriteLibrary.getSprite("bg_game_"+a);t=createBitmap(n);t.regX=n.width/2;t.regY=n.height/2;p.addChild(t);e=new CGoalArea(a-1,p);n=s_oSpriteLibrary.getSprite("ball_holder");var r=createBitmap(n);r.regX=n.width/2;r.regY=n.height/2;r.x=78;r.y=764;p.addChild(r);l=new CBall(0,600,p);
x=new CPlayer(s_oStage);g=new CInterface;g.setControlPos(a-1);q=new createjs.Shape;q.graphics.beginFill("Black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);q.alpha=0;s_oStage.addChild(q);q.on("mousedown",function(){});new CHelpPanel};this._calculateScore=function(n,r,u){var y=0;switch(u){case GREEN_TARGET:y=GREEN_AREA_POINTS;break;case YELLOW_TARGET:y=YELLOW_AREA_POINTS;break;case RED_TARGET:y=RED_AREA_POINTS}d+=y;0<y&&setTimeout(function(){new CScoreText(y,n,r,p)},500);g.refreshScore(d)};this._shiftCamera=
function(n){320<Math.abs(n)&&(n=0<n?320:-320);(new createjs.Tween.get(p)).wait(500).to({scaleX:1,scaleY:1,regX:n},2E3,createjs.Ease.cubicOut);(new createjs.Tween.get(p)).wait(500).to({regY:-200},1300,createjs.Ease.cubicOut).to({regY:-150},1600,createjs.Ease.cubicIn)};this.playerShot=function(n,r){f=n;h=r;x.startPlay()};this.launchBall=function(){c++;g.refreshShot(c);var n=e.getAreaHit(f,h);this._shiftCamera(n.x);l.launch(n.x,n.y,n.areahit,f,n.stakehit)};this.ballTouchTheTarget=function(n,r,u){e.showArea(u);
this._calculateScore(n,r,u);switch(u){case GREEN_TARGET:playSound("goal",1,!1);playSound("green_area",1,!1);new CScoreText(TEXT_CENTER_GREEN,n,r,p,"#17294d");break;case YELLOW_TARGET:playSound("yellow_area",1,!1);new CScoreText(TEXT_CENTER_YELLOW,n,r,p,"#17294d");break;case RED_TARGET:playSound("red_area",1,!1);new CScoreText(TEXT_CENTER_RED,n,r,p,"#17294d");break;case NULL_TARGET_POLE:playSound("miss_goal",1,!1);new CScoreText(TEXT_CENTER_NULL,n,r,p,"#ff0000");break;case NULL_TARGET_LEFT:playSound("miss_goal",
1,!1);new CScoreText(TEXT_WIDE_LEFT,n,r,p,"#ff0000");break;case NULL_TARGET_RIGHT:playSound("miss_goal",1,!1),new CScoreText(TEXT_WIDE_RIGHT,n,r,p,"#ff0000")}u!==NULL_TARGET_POLE&&p.swapChildren(l.getContainer(),e.getContainer())};this.ballArrived=function(n){c>SHOTS_PER_STAGE?($(s_oMain).trigger("end_level",a),c=1,a++,a>NUM_STAGES?m.gameOver():this._changeStage()):m._resetShot();n||p.swapChildren(e.getContainer(),l.getContainer())};this._changeStage=function(){playSound("game_over",1,!1);$(s_oMain).trigger("start_level",
a);(new createjs.Tween.get(q)).to({alpha:1},1E3).call(function(){e.setGoalArea(a-1);e.setAreaSprite(a-1);m._levelSet();g.resetShotsIndicator();g.stopControl();g.setControlPos(a-1);t.image=s_oSpriteLibrary.getSprite("bg_game_"+a);(new createjs.Tween.get(q)).to({alpha:0},1E3).call(function(){g.resetControl(SHOT_INDICATOR_SPEED)})})};this._resetShot=function(){e.stopAnim();(new createjs.Tween.get(p)).to({scaleX:.5,scaleY:.5,regX:0,regY:0},1E3,createjs.Ease.cubicOut).call(function(){m._levelSet()})};
this._levelSet=function(){l.reset();p.scaleX=p.scaleY=.5;p.regX=p.regY=0;var n=SHOT_INDICATOR_SPEED-c*DECREASE_SHOT_INDICATOR_SPEED;n<DECREASE_SHOT_INDICATOR_SPEED&&(n=DECREASE_SHOT_INDICATOR_SPEED);g.refreshStage(a);g.resetControl(n)};this.getStage=function(){return a};this.endGoalAnim=function(){e.stopAnim()};this.unload=function(){g.unload();null!==k&&k.unload();createjs.Tween.removeAllTweens();s_oStage.removeAllChildren();q.off("mousedown")};this.onExit=function(){stopSound("crowd");$(s_oMain).trigger("show_interlevel_ad");
$(s_oMain).trigger("end_session");this.unload();s_oMain.gotoMenu();setVolume("soundtrack",1)};this._onExitHelp=function(){setVolume("soundtrack",0);$(s_oMain).trigger("start_level",1)};this.gameOver=function(){k=CEndPanel(d);k.show()};this.restartGame=function(){m.unload();m._init()};this.update=function(){x.update()};s_oGame=this;SHOT_INDICATOR_SPEED=b.shot_indicator_spd;DECREASE_SHOT_INDICATOR_SPEED=b.decrease_shot_indicator_spd;SHOTS_PER_STAGE=b.shots_per_stage;RED_AREA_POINTS=b.red_area_points;
YELLOW_AREA_POINTS=b.yellow_area_points;GREEN_AREA_POINTS=b.green_area_points;AD_SHOW_COUNTER=b.ad_show_counter;var m=this;this._init()}var s_oGame;
function CInterface(){var b,d,a,c,f,h,g,k,e,l,q,p,t,x;function m(w){w||(w=window.event);switch(w.keyCode){case SPACE_BAR:return K._handleClick(),w.preventDefault(),!1;case LEFT:return w.preventDefault(),!1;case UP:return w.preventDefault(),!1;case RIGHT:return w.preventDefault(),!1;case DOWN:return w.preventDefault(),!1}}var n,r,u,y,v,z,B,F,C,D,E,G,J,H=null,L=null;this._init=function(){n=!0;r=HORIZONTAL_SELECTION_STATE;var w,A=s_oSpriteLibrary.getSprite("but_exit");f=CANVAS_WIDTH-A.height/2-10;h=
A.height/2+10;v=new CGfxButton(f,h,A,s_oStage);v.addEventListener(ON_MOUSE_UP,this._onExit,this);a=w=CANVAS_WIDTH-A.width/2-80;c=A.height/2+10;!1===DISABLE_SOUND_MOBILE||!1===s_bMobile?(A=s_oSpriteLibrary.getSprite("audio_icon"),y=new CToggle(a,c,A,s_bAudioActive,s_oStage),y.addEventListener(ON_MOUSE_UP,this._onAudioToggle,this),A=s_oSpriteLibrary.getSprite("but_fullscreen"),b=a-A.width/2-10,d=c):(A=s_oSpriteLibrary.getSprite("but_fullscreen"),b=w,d=A.height/2+10);w=window.document;var I=w.documentElement;
H=I.requestFullscreen||I.mozRequestFullScreen||I.webkitRequestFullScreen||I.msRequestFullscreen;L=w.exitFullscreen||w.mozCancelFullScreen||w.webkitExitFullscreen||w.msExitFullscreen;!1===ENABLE_FULLSCREEN&&(H=!1);H&&screenfull.enabled&&(J=new CToggle(b,d,A,s_bFullscreen,s_oStage),J.addEventListener(ON_MOUSE_UP,this._onFullscreenRelease,this));D=new CShotIndicatorController(CANVAS_WIDTH/2,300,!1);E=new CShotIndicatorController(500,CANVAS_HEIGHT/2-20,!0);s_bMobile||(document.onkeydown=m);F=new createjs.Shape;
F.graphics.beginFill("Black").drawRect(0,160,CANVAS_WIDTH,CANVAS_HEIGHT-160);F.alpha=.01;s_oStage.addChild(F);F.on("mousedown",this._handleClick,this);this.controlState();q=10;p=62;C=new createjs.Text(TEXT_STAGE+": 1"," 22px "+PRIMARY_FONT,"#17294d");C.textAlign="left";C.textBaseline="alphabetic";C.lineWidth=400;C.x=q;C.y=p;s_oStage.addChild(C);e=10;l=32;z=new createjs.Text(TEXT_SCORE+":"," 22px "+PRIMARY_FONT,"#17294d");z.y=C.y+100;z.textAlign="left";z.textBaseline="alphabetic";z.lineWidth=400;z.x=
e;z.y=l;s_oStage.addChild(z);g=e+z.getMeasuredWidth()+50;k=32;B=new createjs.Text(0," 22px "+PRIMARY_FONT,"#17294d");B.textAlign="left";B.textBaseline="alphabetic";B.lineWidth=400;B.x=g;B.y=k;s_oStage.addChild(B);t=CANVAS_WIDTH-30;x=CANVAS_HEIGHT-30;G=new createjs.Container;G.x=t;G.y=x;s_oStage.addChild(G);A=s_oSpriteLibrary.getSprite("ball");w=A.width/2;I=A.height/6;A=new createjs.SpriteSheet({images:[A],framerate:30,frames:{width:w,height:I,regX:w/2,regY:I/2},animations:{"static":[0]}});u=[];for(w=
0;w<SHOTS_PER_STAGE;w++)u[w]=createSprite(A,"static",0,0,0,0),u[w].gotoAndStop("static"),u[w].scaleX=u[w].scaleY=.15,u[w].rotation=30,u[w].x=26*-w,G.addChild(u[w]);this.refreshButtonPos(s_iOffsetX,s_iOffsetY)};this.unload=function(){if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)y.unload(),y=null;H&&screenfull.enabled&&J.unload();F.off("mousedown");v.unload();s_oInterface=null};this._handleClick=function(w){if(!0===n)switch(r){case HORIZONTAL_SELECTION_STATE:s_oGame.endGoalAnim();D.endAnimation();r++;
K.controlState();break;case VERTICAL_SELECTION_STATE:E.endAnimation(),r++,K.controlState()}};this.controlState=function(){switch(r){case HORIZONTAL_SELECTION_STATE:D.startAnimation();break;case VERTICAL_SELECTION_STATE:E.startAnimation();break;case SHOT_SELECTION_STATE:D.hide(),E.hide(),s_oGame.playerShot(D.getCursorPosition(),E.getCursorPosition())}};this.refreshButtonPos=function(w,A){v.setPosition(f-w,A+h);!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||y.setPosition(a-w,A+c);H&&screenfull.enabled&&
J.setPosition(b-s_iOffsetX,d+s_iOffsetY);C.x=q+w;C.y=p+A;z.x=e+w;z.y=l+A;B.x=g+w;B.y=k+A;G.x=t-w;G.y=x-A};this.refreshScore=function(w){new CRollingTextController(B,null,w,1500,EASE_CUBIC_OUT)};this.refreshStage=function(w){C.text=TEXT_STAGE+": "+w};this.refreshShot=function(w){u[SHOTS_PER_STAGE-(w-1)].visible=!1};this.resetShotsIndicator=function(){for(var w=0;w<SHOTS_PER_STAGE;w++)u[w].visible=!0};this.setControlPos=function(w){D.setPos(CANVAS_WIDTH/2+GOAL_AREA[w].x/2,CANVAS_HEIGHT/2+GOAL_AREA[w].y/
2+Y_BAR_OFFSET[w],GREEN_INDICATOR_RANGE[w]);E.setPos(CANVAS_WIDTH/2+GOAL_AREA[w].x/2+200,CANVAS_HEIGHT/2+GOAL_AREA[w].y/2,GREEN_INDICATOR_RANGE[w])};this.stopControl=function(){D.hide();D.endAnimation();E.hide();E.endAnimation()};this.resetControl=function(w){r=0;D.reset(w);E.reset(w);D.show();E.show();D.startAnimation()};this._onAudioToggle=function(){Howler.mute(s_bAudioActive);s_bAudioActive=!s_bAudioActive};this._onExit=function(){new CAreYouSurePanel(s_oStage)};this.resetFullscreenBut=function(){H&&
screenfull.enabled&&J.setActive(s_bFullscreen)};this._onFullscreenRelease=function(){s_bFullscreen?L.call(window.document):H.call(window.document.documentElement);sizeHandler()};s_oInterface=this;this._init();var K=this;return this}var s_oInterface=null;
function CHelpPanel(){var b,d,a,c,f,h,g;this._init=function(){h=new createjs.Shape;h.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);h.alpha=.7;h.on("mousedown",this._onExitHelp);s_oStage.addChild(h);g=new createjs.Container;s_oStage.addChild(g);var e=s_oSpriteLibrary.getSprite("msg_box"),l=createBitmap(e);l.regX=e.width/2;l.regY=e.height/2;g.addChild(l);g.x=CANVAS_WIDTH/2;g.y=CANVAS_HEIGHT+e.height/2;b=g.y;(new createjs.Tween.get(g)).to({y:CANVAS_HEIGHT/2},500,createjs.Ease.quartIn).call(function(){});
e=TEXT_HELP1;s_bMobile&&(e=TEXT_HELP1_MOB);a=new createjs.Text(e," 16px "+PRIMARY_FONT,"#000000");a.x=2;a.y=-98;a.textAlign="center";a.textBaseline="alphabetic";a.lineWidth=400;d=new createjs.Text(e," 16px "+PRIMARY_FONT,"#ffffff");d.x=0;d.y=-100;d.textAlign="center";d.textBaseline="alphabetic";d.lineWidth=400;e=new createjs.Container;e.x=0;e.y=0;g.addChild(e);l=s_oSpriteLibrary.getSprite("top_bar");var q=createBitmap(l);q.regX=l.width/2;q.regY=l.height/2;e.addChild(q);l=s_oSpriteLibrary.getSprite("arrow_bar");
q=createBitmap(l);q.regX=l.width/2;q.regY=l.height;q.x=-20;e.addChild(q);l=s_oSpriteLibrary.getSprite("arrow");q=createBitmap(l);q.regX=l.width/2;q.regY=5;q.x=-25;e.addChild(q);l=s_oSpriteLibrary.getSprite("arrow");q=createBitmap(l);q.regX=l.width/2;q.regY=5;q.x=25;e.addChild(q);f=new createjs.Text(TEXT_HELP2," 16px "+PRIMARY_FONT,"#000000");f.x=-198;f.y=52;f.textAlign="left";f.textBaseline="alphabetic";f.lineWidth=300;c=new createjs.Text(TEXT_HELP2," 16px "+PRIMARY_FONT,"#ffffff");c.x=-200;c.y=50;
c.textAlign="left";c.textBaseline="alphabetic";c.lineWidth=300;e=s_oSpriteLibrary.getSprite("green_area_3");e=new createjs.SpriteSheet({images:[e],frames:{width:e.width/2,height:e.height,regX:e.width/2/2,regY:e.height/2},animations:{off:[0],on:[1]}});e=new createjs.Sprite(e);e.gotoAndStop("on");e.x=160;e.y=65;e.scaleX=e.scaleY=.8;g.addChild(e);g.addChild(d,c)};this.unload=function(){s_oStage.removeChild(g);h.off("mousedown");s_oStage.removeChild(h)};this._onExitHelp=function(){(new createjs.Tween.get(h)).to({alpha:0},
500);(new createjs.Tween.get(g)).to({y:b},400,createjs.Ease.backIn).call(function(){k.unload();s_oGame._onExitHelp()})};var k=this;this._init()}
function CCreditsPanel(){var b,d,a,c,f,h;this._init=function(){d=new createjs.Shape;d.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);d.alpha=0;h=d.on("click",this._onLogoButRelease);s_oStage.addChild(d);(new createjs.Tween.get(d)).to({alpha:.7},500);a=new createjs.Container;s_oStage.addChild(a);var g=s_oSpriteLibrary.getSprite("msg_box"),k=createBitmap(g);k.regX=g.width/2;k.regY=g.height/2;a.addChild(k);a.x=CANVAS_WIDTH/2;a.y=CANVAS_HEIGHT+g.height/2;b=a.y;(new createjs.Tween.get(a)).to({y:CANVAS_HEIGHT/
2-40},500,createjs.Ease.quartIn);k=new createjs.Text("DEVELOPED BY"," 20px "+PRIMARY_FONT,"#ffffff");k.y=-g.height/2+60;k.textAlign="center";k.textBaseline="middle";k.lineWidth=300;a.addChild(k);g=new createjs.Text("www.codethislab.com"," 20px "+PRIMARY_FONT,"#ffffff");g.y=70;g.textAlign="center";g.textBaseline="middle";g.lineWidth=300;a.addChild(g);g=new createjs.Text("v.2"," 12px "+PRIMARY_FONT,"#ffffff");g.x=-200;g.y=110;g.textAlign="center";g.textBaseline="middle";g.lineWidth=300;a.addChild(g);
g=s_oSpriteLibrary.getSprite("ctl_logo");f=createBitmap(g);f.regX=g.width/2;f.regY=g.height/2;a.addChild(f);g=s_oSpriteLibrary.getSprite("but_exit");c=new CGfxButton(193,-90,g,a);c.addEventListener(ON_MOUSE_UP,this.unload,this)};this.unload=function(){c.setClickable(!1);(new createjs.Tween.get(d)).to({alpha:0},500);(new createjs.Tween.get(a)).to({y:b},400,createjs.Ease.backIn).call(function(){s_oStage.removeChild(d);s_oStage.removeChild(a);c.unload()});d.off("click",h)};this._onLogoButRelease=function(){};
this._onMoreGamesReleased=function(){};this._init()}
function CAreYouSurePanel(){var b,d,a,c,f;this._init=function(){c=new createjs.Shape;c.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);c.alpha=0;c.on("mousedown",function(){});s_oStage.addChild(c);(new createjs.Tween.get(c)).to({alpha:.7},500);f=new createjs.Container;s_oStage.addChild(f);var g=s_oSpriteLibrary.getSprite("msg_box"),k=createBitmap(g);k.regX=g.width/2;k.regY=g.height/2;f.addChild(k);f.x=CANVAS_WIDTH/2;f.y=CANVAS_HEIGHT+g.height/2;b=f.y;(new createjs.Tween.get(f)).to({y:CANVAS_HEIGHT/
2-40},500,createjs.Ease.quartIn);k=new createjs.Text(TEXT_ARE_SURE,"34px "+PRIMARY_FONT,"#ffffff");k.y=-g.height/2+60;k.textAlign="center";k.textBaseline="middle";k.lineWidth=400;f.addChild(k);d=new CGfxButton(110,60,s_oSpriteLibrary.getSprite("but_yes_big"),f);d.addEventListener(ON_MOUSE_UP,this._onButYes,this);a=new CGfxButton(-110,60,s_oSpriteLibrary.getSprite("but_exit_big"),f);a.addEventListener(ON_MOUSE_UP,this._onButNo,this);a.pulseAnimation()};this._onButYes=function(){a.setClickable(!1);
d.setClickable(!1);(new createjs.Tween.get(c)).to({alpha:0},500);(new createjs.Tween.get(f)).to({y:b},400,createjs.Ease.backIn).call(function(){h.unload();s_oGame.onExit()})};this._onButNo=function(){a.setClickable(!1);d.setClickable(!1);(new createjs.Tween.get(c)).to({alpha:0},500);(new createjs.Tween.get(f)).to({y:b},400,createjs.Ease.backIn).call(function(){h.unload()})};this.unload=function(){a.unload();d.unload();s_oStage.removeChild(c);s_oStage.removeChild(f);c.off("mousedown",function(){})};
var h=this;this._init()}
function CEndPanel(b){var d,a,c,f,h;this._init=function(k){a=new createjs.Shape;a.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);a.alpha=0;a.on("mousedown",function(){});s_oStage.addChild(a);(new createjs.Tween.get(a)).to({alpha:.7},500);c=new createjs.Container;s_oStage.addChild(c);var e=s_oSpriteLibrary.getSprite("msg_box"),l=createBitmap(e);l.regX=e.width/2;l.regY=e.height/2;c.addChild(l);c.x=CANVAS_WIDTH/2;c.y=CANVAS_HEIGHT+e.height/2;d=c.y;(new createjs.Tween.get(c)).to({y:CANVAS_HEIGHT/2},
500,createjs.Ease.quartIn);l=new createjs.Text(TEXT_GAMEOVER," 26px "+PRIMARY_FONT,"#ffffff");l.y=-e.height/2+50;l.textAlign="center";l.textBaseline="middle";l.lineWidth=400;c.addChild(l);$(s_oMain).trigger("save_score",k);$(s_oMain).trigger("share_event",k);k=new createjs.Text(TEXT_TOTAL_SCORE+" "+k," 20px "+PRIMARY_FONT,"#ffffff");k.y=l.y+40;k.textAlign="center";k.textBaseline="middle";k.lineWidth=500;c.addChild(k);e=s_oSpriteLibrary.getSprite("but_home");f=new CGfxButton(-120,60,e,c);f.addEventListener(ON_MOUSE_UP,
this._onExit,this);e=s_oSpriteLibrary.getSprite("but_restart");h=new CGfxButton(120,60,e,c);h.addEventListener(ON_MOUSE_UP,this._onRestart,this);h.pulseAnimation()};this.unload=function(){s_oStage.removeChild(c);a.off("mousedown",function(){});f.unload();h.unload()};this.show=function(k){playSound("game_over",1,!1)};this._onExit=function(){a.off("mousedown",function(){});s_oStage.removeChild(c);s_oGame.onExit()};this._onRestart=function(){(new createjs.Tween.get(a)).to({alpha:0},500);(new createjs.Tween.get(c)).to({y:d},
400,createjs.Ease.backIn).call(function(){g.unload();s_oGame.restartGame()})};var g=this;this._init(b);return this}
function CShotIndicatorController(b,d,a){var c,f,h=!0,g,k,e,l,q,p,t,x;this.init=function(m,n,r){l=new createjs.Container;l.x=m;l.y=n;s_oStage.addChild(l);g=r;!1===r?(m=s_oSpriteLibrary.getSprite("top_bar"),q=createBitmap(m),q.regX=m.width/2,q.regY=m.height/2,l.addChild(q),c=-m.width/2+4,f=m.width/2-4,e=f-c,m=s_oSpriteLibrary.getSprite("arrow_bar"),p=createBitmap(m),p.regX=m.width/2,p.regY=m.height/2+20,p.x=c,l.addChild(p),m=s_oSpriteLibrary.getSprite("arrow"),t=createBitmap(m),t.regX=m.width/2,t.regY=
5,l.addChild(t),m=s_oSpriteLibrary.getSprite("arrow"),x=createBitmap(m),x.regX=m.width/2,x.regY=5):(m=s_oSpriteLibrary.getSprite("right_bar"),q=createBitmap(m),q.regX=m.width/2,q.regY=m.height/2,l.addChild(q),c=-m.height/2+1,f=m.height/2-6,e=f-c,m=s_oSpriteLibrary.getSprite("arrow_bar"),p=createBitmap(m),p.regX=m.width/2,p.regY=m.height/2+20,p.y=c,p.rotation=90,l.addChild(p),m=s_oSpriteLibrary.getSprite("arrow"),t=createBitmap(m),t.regX=m.width/2,t.regY=4,t.rotation=90,l.addChild(t),m=s_oSpriteLibrary.getSprite("arrow"),
x=createBitmap(m),x.regX=m.width/2,x.regY=4,x.rotation=90);l.addChild(x);this.reset(SHOT_INDICATOR_SPEED)};this.reset=function(m){k=m;g?p.y=c:p.x=c};this.show=function(){h=!0;l.visible=h};this.hide=function(){h=!1;l.visible=h};this.getCursorPosition=function(){return g?(p.y-c)/(f-c)*2-1:(p.x-c)/(f-c)*2-1};this.startAnimation=function(){g?(new createjs.Tween.get(p,{loop:!0})).to({y:c+.5*e},k/2,createjs.Ease.cubicIn).to({y:f},.5*k,createjs.Ease.cubicOut).to({y:c+.5*e},k/2,createjs.Ease.cubicIn).to({y:c},
.5*k,createjs.Ease.cubicOut):(new createjs.Tween.get(p,{loop:!0})).to({x:c+.5*e},k/2,createjs.Ease.cubicIn).to({x:f},.5*k,createjs.Ease.cubicOut).to({x:c+.5*e},k/2,createjs.Ease.cubicIn).to({x:c},.5*k,createjs.Ease.cubicOut)};this.setPos=function(m,n,r){l.x=m;l.y=n;a?(t.y=r.vert.top,x.y=r.vert.bot):(t.x=r.horiz.left,x.x=r.horiz.right)};this.endAnimation=function(){new createjs.Tween.removeTweens(p)};this.init(b,d,a)}
function CVector2(b,d){var a,c;this._init=function(f,h){a=f;c=h};this.add=function(f,h){a+=f;c+=h};this.addV=function(f){a+=f.getX();c+=f.getY()};this.scalarDivision=function(f){a/=f;c/=f};this.subV=function(f){a-=f.getX();c-=f.getY()};this.scalarProduct=function(f){a*=f;c*=f};this.invert=function(){a*=-1;c*=-1};this.dotProduct=function(f){return a*f.getX()+c*f.getY()};this.set=function(f,h){a=f;c=h};this.setV=function(f){a=f.getX();c=f.getY()};this.length=function(){return Math.sqrt(a*a+c*c)};this.length2=
function(){return a*a+c*c};this.normalize=function(){var f=this.length();0<f&&(a/=f,c/=f)};this.getNormalize=function(f){this.length();f.set(a,c);f.normalize()};this.rot90CCW=function(){var f=a;a=-c;c=f};this.rot90CW=function(){var f=a;a=c;c=-f};this.getRotCCW=function(f){f.set(a,c);f.rot90CCW()};this.getRotCW=function(f){f.set(a,c);f.rot90CW()};this.ceil=function(){a=Math.ceil(a);c=Math.ceil(c)};this.round=function(){a=Math.round(a);c=Math.round(c)};this.toString=function(){return"Vector2: "+a+", "+
c};this.print=function(){trace("Vector2: "+a+", "+c)};this.getX=function(){return a};this.getY=function(){return c};this._init(b,d)}
function CGoalArea(b,d){var a,c,f,h,g,k,e,l,q,p,t;this._init=function(m,n){a=m;c=new createjs.Container;n.addChild(c);t=new createjs.Container;n.addChild(t);this.setGoalArea(a);this.setAreaSprite(a)};this.unload=function(){d.removeChild(c);d.removeChild(t)};this.setGoalArea=function(m){a=m;c.removeAllChildren();t.removeAllChildren();d.removeChild(p);c.x=GOAL_AREA[a].x;c.y=GOAL_AREA[a].y;f=new createjs.Shape;f.graphics.beginFill("rgba(0,255,255,0.5)").drawRect(-GOAL_AREA[a].width/2,-GOAL_AREA[a].height/
2,GOAL_AREA[a].width,GOAL_AREA[a].height)};this.setAreaSprite=function(){var m=a+1,n=s_oSpriteLibrary.getSprite("green_area_"+m);n={images:[n],frames:{width:n.width/2,height:n.height,regX:n.width/2/2+TARGET_AREA_SPRITE_OFFSET[a].green.x,regY:n.height/2+TARGET_AREA_SPRITE_OFFSET[a].green.y},animations:{off:[0],on:[1]}};n=new createjs.SpriteSheet(n);k=new createjs.Sprite(n);c.addChild(k);q=new createjs.Sprite(n);q.gotoAndStop("on");q.alpha=0;c.addChild(q);n=s_oSpriteLibrary.getSprite("yellow_area_"+
m);n={images:[n],frames:{width:n.width/2,height:n.height,regX:n.width/2/2+TARGET_AREA_SPRITE_OFFSET[a].yellow.x,regY:n.height/2+TARGET_AREA_SPRITE_OFFSET[a].yellow.y},animations:{off:[0],on:[1]}};n=new createjs.SpriteSheet(n);g=new createjs.Sprite(n);c.addChild(g);l=new createjs.Sprite(n);l.gotoAndStop("on");l.alpha=0;c.addChild(l);n=s_oSpriteLibrary.getSprite("red_area_"+m);n={images:[n],frames:{width:n.width/2,height:n.height,regX:n.width/2/2,regY:n.height/2},animations:{off:[0],on:[1]}};n=new createjs.SpriteSheet(n);
h=new createjs.Sprite(n);c.addChild(h);e=new createjs.Sprite(n);e.gotoAndStop("on");e.alpha=0;c.addChild(e);this._stakeArea();this.animateArea()};this._stakeArea=function(){var m=new createjs.Shape;m.graphics.setStrokeStyle(50);m.graphics.beginStroke("rgba(255,255,255,0.01)");m.graphics.moveTo(STAKE_POS[a][0].x,STAKE_POS[a][0].y);for(var n=1;n<STAKE_POS[a].length;n++)m.graphics.lineTo(STAKE_POS[a][n].x,STAKE_POS[a][n].y);t.addChild(m);m=s_oSpriteLibrary.getSprite("post_"+(a+1));p=createBitmap(m);
p.regX=m.width/2;p.regY=m.height/2;p.x=POST_POS[a].x-GOAL_AREA[a].x;p.y=POST_POS[a].y-GOAL_AREA[a].y;c.addChild(p)};this.getAreaHit=function(m,n){var r=GOAL_AREA[a].x+m*GOAL_AREA[a].width/2,u=GOAL_AREA[a].y+n*GOAL_AREA[a].height/2;if(t.hitTest(r,u))return{x:r,y:u,areahit:NULL_TARGET_POLE,stakehit:!0};var y=m*GOAL_AREA[a].width/2,v=n*GOAL_AREA[a].height/2;y=k.hitTest(y,v)?GREEN_TARGET:g.hitTest(y,v)?YELLOW_TARGET:h.hitTest(y,v)?RED_TARGET:0>m?NULL_TARGET_LEFT:NULL_TARGET_RIGHT;return{x:r,y:u,areahit:y,
stakehit:!1}};this.showArea=function(m){switch(m){case GREEN_TARGET:(new createjs.Tween.get(q)).to({alpha:.8},100).to({alpha:0},100).to({alpha:1},50);break;case YELLOW_TARGET:(new createjs.Tween.get(l)).to({alpha:.8},100).to({alpha:0},100).to({alpha:1},50);break;case RED_TARGET:(new createjs.Tween.get(e)).to({alpha:.8},100).to({alpha:0},100).to({alpha:1},50)}};this.getGlobalPos=function(){return d.localToGlobal(c.x,c.y)};this.animateArea=function(){this._anim3(1500)};this._anim=function(m){(new createjs.Tween.get(e)).to({alpha:1},
m).call(function(){(new createjs.Tween.get(l)).to({alpha:1},m);(new createjs.Tween.get(e)).to({alpha:0},m).call(function(){(new createjs.Tween.get(q)).to({alpha:1},m);(new createjs.Tween.get(l)).to({alpha:0},m).call(function(){(new createjs.Tween.get(q)).to({alpha:0},m);x._anim(m)})})})};this._anim2=function(m){(new createjs.Tween.get(e)).to({alpha:1},m).to({alpha:0},m);(new createjs.Tween.get(l)).wait(m/2).to({alpha:1},m).to({alpha:0},m);(new createjs.Tween.get(q)).wait(m).to({alpha:1},m).to({alpha:0},
m).call(function(){x._anim2(m)})};this._anim3=function(m){(new createjs.Tween.get(e)).to({alpha:1},m,createjs.Ease.cubicOut).to({alpha:0},m,createjs.Ease.cubicIn);(new createjs.Tween.get(l)).wait(m/2).to({alpha:1},m,createjs.Ease.cubicOut).to({alpha:0},m,createjs.Ease.cubicIn);(new createjs.Tween.get(q)).wait(m).to({alpha:1},m,createjs.Ease.cubicOut).to({alpha:0},m,createjs.Ease.cubicIn).call(function(){x._anim2(m)})};this.stopAnim=function(){(new createjs.Tween.get(e,{override:!0})).to({alpha:0},
800);(new createjs.Tween.get(l,{override:!0})).to({alpha:0},800);(new createjs.Tween.get(q,{override:!0})).to({alpha:0},800)};this.getContainer=function(){return c};var x=this;this._init(b,d)}
function CBall(b,d,a){var c,f,h;this._init=function(k,e,l){c=2;f=new createjs.Container;f.x=k;f.y=e;l.addChild(f);k=s_oSpriteLibrary.getSprite("ball");e=k.width/2;l=k.height/6;k=new createjs.SpriteSheet({images:[k],framerate:30,frames:{width:e,height:l,regX:e/2,regY:l/2},animations:{launch:[0,11,"launch"]}});h=createSprite(k,"launch",0,0,0,0);h.gotoAndStop("launch");f.addChild(h)};this.unload=function(){a.removeChild(f)};this.launch=function(k,e,l,q,p){h.gotoAndPlay("launch");h.framerate=30;var t=
BALL_FLYTIME;q*=BALL_MAX_ROTATION;(new createjs.Tween.get(f)).to({rotation:q},t,createjs.Ease.cubicOut);(new createjs.Tween.get(f)).to({x:k},t,createjs.Ease.cubicOut);(new createjs.Tween.get(f)).to({y:e},.5*t,createjs.Ease.cubicOut).call(function(){p?(new createjs.Tween.removeTweens(f),h.framerate=10,s_oGame.ballTouchTheTarget(f.x,f.y,l),(new createjs.Tween.get(f)).to({y:e+400,alpha:0},.5*t,createjs.Ease.cubicIn),(new createjs.Tween.get(f)).to({scaleX:f.scaleX+.1,scaleY:f.scaleY+.1},.5*t).wait(1E3).call(function(){s_oGame.ballArrived(p);
new createjs.Tween.removeTweens(f);h.gotoAndStop("launch")})):((new createjs.Tween.get(f)).to({y:e+200,alpha:0},.5*t,createjs.Ease.cubicIn),s_oGame.ballTouchTheTarget(f.x,f.y,l),l>NULL_TARGET_POLE&&g._waveAnimation(f.x,f.y))});(new createjs.Tween.get(f)).to({scaleX:.02,scaleY:.02},t,createjs.Ease.cubicOut).wait(1E3).call(function(){s_oGame.ballArrived();new createjs.Tween.removeTweens(f);h.gotoAndStop("launch")})};this.reset=function(){f.alpha=1;f.scaleX=f.scaleY=1;f.rotation=0;f.x=b;f.y=d};this._waveAnimation=
function(k,e){0===c?c=2:(this.spawnWave(k,e),setTimeout(function(){g._waveAnimation(k,e)},200))};this.spawnWave=function(k,e){c--;var l=new createjs.Shape;l.graphics.setStrokeStyle(3);l.graphics.beginStroke("rgba(255,255,255,1)").drawCircle(k,e,1);a.addChild(l);(new createjs.Tween.get(l.graphics.command)).to({radius:50},1E3,createjs.Ease.cubicOut);(new createjs.Tween.get(l)).to({alpha:0},1E3,createjs.Ease.cubicOut).call(function(){a.removeChild(l)})};this.getContainer=function(){return f};var g=this;
this._init(b,d,a)}
function CPlayer(b){var d,a,c,f,h;this._init=function(g){a=d=!1;c=0;h=new createjs.Container;h.y=CANVAS_HEIGHT;g.addChild(h);f=[];for(g=0;37>=g;g++){var k=s_oSpriteLibrary.getSprite("player_"+g);f[g]=createBitmap(k);f[g].regY=k.height;f[g].visible=!1;h.addChild(f[g])}};this.unload=function(){b.removeChild(h)};this.fade=function(){(new createjs.Tween.get(h)).to({alpha:0},800)};this.startPlay=function(){h.alpha=1;d=!0;a=!1};this._playShot=function(){0!==c&&(f[c-1].visible=!1);f[c].visible=!0;c++;12<=
c&&!a&&(a=!0,playSound("kick",1,!1),s_oGame.launchBall(),this.fade());37<c&&(f[c-1].visible=!1,c=0,d=!1)};this.update=function(){d&&this._playShot()};this._init(b)}
function CScoreText(b,d,a,c,f){var h;this._init=function(g,k,e,l){h=new createjs.Text("00000"," 30px "+PRIMARY_FONT,"#17294d");h.textAlign="center";h.text=0<=g?"+"+g:g;h.color=f;h.x=k;h.y=e;h.alpha=0;h.shadow=new createjs.Shadow("#ffffff",2,2,2);l.addChild(h);var q=this;createjs.Tween.get(h).to({alpha:1},400,createjs.Ease.quadIn).call(function(){q.moveUp()})};this.moveUp=function(){var g=h.y-100,k=this;createjs.Tween.get(h).to({y:g},1E3,createjs.Ease.sineIn).call(function(){k.unload()});createjs.Tween.get(h).wait(500).to({alpha:0},
500)};this.unload=function(){c.removeChild(h)};this._init(b,d,a,c)};